# Generated by Django 5.0.6 on 2024-06-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='user',
            field=models.CharField(default='user', max_length=1000000),
        ),
    ]
